# Book settings
title: Programming Differential Privacy
author: Joseph P. Near and Chik√© Abuah
copyright: "2021"
logo: notebooks/logo.png

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

bibtex_bibfiles:
    - references.bib

repository:
  url: https://github.com/uvm-plaid/programming-dp
  branch: master
